# Write your MySQL query statement below
SELECT D.NAME AS Department, E.NAME AS Employee, E.SALARY AS Salary FROM Employee E
JOIN Department D
ON E.DEPARTMENTID=D.ID
WHERE 3>(SELECT COUNT(DISTINCT(E1.SALARY)) FROM EMPLOYEE E1
WHERE E1.SALARY>E.SALARY AND E1.DEPARTMENTID=E.DEPARTMENTID)
ORDER BY 1,3 DESC